> ## **5-2 신경망학습 (4/2)**

In [1]:
import numpy as np
from functions import softmax, cross_entropy_error
from numerical_gradient import numerical_gradient_1d

In [3]:
def numerical_gradient_2d(f,X):
    if X.ndim == 1:
        return numerical_gradient_1d(f,X)
    else:
        grad = np.zeros_like(X) 

        for idx, x in enumerate(X):
            grad[idx] = numerical_gradient_1d(f,x) #행 마다 gradient를 각각 실행시켜준다

        return grad

In [5]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(3,3)

    def predict(self, x):
        b = [1] if x.ndim == 1 else np.ones(x.shape[0], 1)
        x = np.append(b, x, axis=x.ndim-1)
        return np.dot(x, self.W)
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y,t)
        return loss

In [7]:
net = simpleNet()
print(net.W)

[[ 0.50338959 -0.02517279  0.37410828]
 [-0.21652252  0.8138638   1.16338213]
 [-0.22127259 -0.76564115  0.1110517 ]]


In [9]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p) # [-1.50844869  1.16179933 -0.99451474] -> 2번 클래스의 predict값이 가장 높음

[ 0.17433074 -0.22593155  1.17208409]


In [11]:
xx = np.append([1],x)
np.dot(xx, net.W)

array([ 0.17433074, -0.22593155,  1.17208409])

In [13]:
print(np.argmax(p)) # 가장 높은 값을 나타내는 index번호
t = np.array([0, 0, 1]) # 정답 array는 3번째인 2번 index가 정답
print(net.loss(x,t)) # 틀렸으므로 loss값이 큰것

2
0.4798261000025769


In [15]:
def f(W):
    return net.loss(x,t)

In [17]:
dW = numerical_gradient_2d(f, net.W) # 따라서 손실값을 줄일 수 있도록 gradient를 실행해준다
print(dW)

[[ 0.22818929  0.15291974 -0.38110903]
 [ 0.13691357  0.09175184 -0.22866542]
 [ 0.20537036  0.13762777 -0.34299813]]
