In [ ]:
# N차원 배열(tensor)
# 2차원 numpy 배열(행렬) 생성

In [22]:
import numpy as np

In [26]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [28]:
A.shape

(2, 2)

In [30]:
A.dtype

dtype('int32')

In [32]:
# 원소별 연산
import numpy as np

In [46]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,1],[1,6]])

In [48]:
print(A)
print(B)

[[1 2]
 [3 4]]
[[3 1]
 [1 6]]


In [38]:
A+B

array([[ 4,  3],
       [ 4, 10]])

In [40]:
A-B

array([[-2,  1],
       [ 2, -2]])

In [42]:
A*B #파이썬에서의 행렬 곱은 그냥 원소끼리의 곱이다.

array([[ 3,  2],
       [ 3, 24]])

In [44]:
A/B

array([[0.33333333, 2.        ],
       [3.        , 0.66666667]])