<span style= "color:red; font-size:30px">산술 연산(Element-wise product)</span><br>
1. <span style= "color:blue; font-size:22px">원소별 연산(Element-wise product)</span>
    * 동일한 형태의 numpy 배열 사이 산술연산

In [45]:
import numpy as np

In [47]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 2.0, 3.0])

In [49]:
x+y

array([3., 4., 6.])

In [51]:
x-y

array([-1.,  0.,  0.])

In [53]:
x*y

array([2., 4., 9.])

In [55]:
x/y

array([0.5, 1. , 1. ])

2. <span style= "color:blue; font-size:22px">브로드캐스팅(Broadcasting)</span>
    * Numpy 배열과 스칼라 값의 산술연산

In [57]:
import numpy as np

In [59]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])


In [61]:
x+2.0

array([3., 4., 5.])

In [63]:
x-2

array([-1.,  0.,  1.])

In [65]:
x*2

array([2., 4., 6.])

In [67]:
x/2

array([0.5, 1. , 1.5])