In [11]:
import numpy as np

In [19]:
X = np.arange(12).reshape(3,-1)
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
X[0]

array([10, 11, 12, 13])

In [17]:
X[1,2]

16

In [21]:
# 슬라이싱
X[1:3, 2:4]

array([[ 6,  7],
       [10, 11]])

In [25]:
print(X)
for row in X:
    print(row)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [31]:
Y = X.flatten() + 1
print(Y)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [33]:
# indices(해당 번쨰 인덱스 값을 색출해낸다)
indices = [1, 4, 7]
print(Y[indices])

[2 5 8]


In [35]:
print(Y>15)
#각 인덱스 값이 해당조건에 만족하는지 참 거짓 판단
# a = Y > 15
# print(a)
print(Y[Y>15])

[False False False False False False False False False False False False]
[]


In [ ]:
# 행렬 곱 해주는 연산자
print(A)
print(B)
np.dot(A,B) 
# print(np.dot(A,B))
# print(B.dot(A))