In [2]:
import numpy as np

In [4]:
a = np.array([0.3,2.9,4.0])

exp_a = np.exp(a)
# e^(a[i])의 값
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [6]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542101633


In [8]:
y = exp_a/sum_exp_a
print(y)
print(np.sum(y))

[0.01821127 0.24519181 0.73659691]
1.0


In [ ]:
def softmax_func(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a/sum_exp_a
    return y

In [12]:
print(softmax_func(a))

[0.01821127 0.24519181 0.73659691]


In [16]:
def softmax_func(a):
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a/sum_exp_a
    return y

C:\Users\guddn\AppData\Local\Temp\ipykernel_25240\3105132050.py:2: RuntimeWarning: overflow encountered in exp
  exp_a = np.exp(a)
C:\Users\guddn\AppData\Local\Temp\ipykernel_25240\3105132050.py:4: RuntimeWarning: invalid value encountered in divide
  y = exp_a/sum_exp_a


array([nan, nan, nan])

In [ ]:
a = np.array([1010, 1000, 990]) -> 값이 너무 커져서 오버플로우 발생
softmax_func(a)