In [2]:
import numpy as np
from functions import softmax, cross_entropy_error
from numerical_gradient import numerical_gradient_1d

In [4]:
def numerical_gradient_2d(f, X):
    if X.ndim == 1:
        return numerical_gradient_1d(f, X)
    else:
        grad = np.zeros_like(X)
        
        for idx, x in enumerate(X):
            grad[idx] = numerical_gradient_1d(f, x)
        
        return grad

In [6]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(3,3)
        
    def predict(self, x):
        b = [1] if x.ndim==1 else np.ones(x.shape[0], 1)
        x = np.append(b, x, axis=x.ndim-1)
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y,t)
        return loss

In [8]:
net = simpleNet()
print(net.W)

[[-1.86540578 -0.98795462  1.33040058]
 [ 0.11365797 -0.99034601  0.7424222 ]
 [ 0.41550943  0.33774776  0.34596394]]


In [10]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

[-1.42325251 -1.27818924  2.08722144]


In [12]:
print(np.argmax(p))
t = np.array([0, 0, 1])
print(net.loss(x,t))

2
0.06243987650665016


In [14]:
def f(W):
    return net.loss(x,t)

In [16]:
dW = numerical_gradient_2d(f, net.W)
print(dW)

[[ 0.02807393  0.03245662 -0.06053055]
 [ 0.01684436  0.01947397 -0.03631833]
 [ 0.02526653  0.02921096 -0.05447749]]
